run:
	symfony server:start
load:
	php bin/console doctrine:fixtures:load --append
entity:
	php bin/console make:entity
controller:
	php bin/console make:controller
user:
	php bin/console make:controller
